version: '3.8'
services:
  php:
    restart: always
    build: ./
    ports:
      - "8080:8080"
    networks:
      service_network:
    volumes:
      - ./:/var/www/html/
    # depends_on:
    #   - mysql
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: kaito
      MYSQL_DATABASE: shop
    networks:
      service_network:
    volumes:
      - ./.docker/mysql/my.conf:/etc/mysql/conf.d/my.conf:ro
      - ./.docker/mysql/shop.sql:/docker-entrypoint-initdb.d/shop.sql
      - mysqldata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    volumes:
      - phpmyadmindata:/var/www/html
    depends_on:
      - mysql
networks:
  service_network:
volumes:
  mysqldata:
  phpmyadmindata: