version: '3.8'

services:
  nginx:
    image: nginx:1.18.0-alpine
    ports:
      - 80:80
    volumes:
      - ./:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      # - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    build: ./.docker/php
    working_dir: /var/www/php
    volumes:
      - ./:/var/www/php
    depends_on:
      - mysql

  mysql:
    # image: mysql:8
    build: ./.docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: kaito
      MYSQL_DATABASE: shop
    volumes:
      - ./.docker/mysql/my.conf:/etc/mysql/conf.d/my.conf:ro
      - ./.docker/mysql/shop.sql:/docker-entrypoint-initdb.d/shop.sql
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysqldata:
